companies = {
    'MMM': '3M co',
    'T': 'AT&T Inc',
    'ADBE': 'Adobe Systems Inc.',
    'AA': 'Alcoa Inc',
    'GOOG': 'Alphabet Inc',
    'AXP': 'American Express',
    'AIG': 'American Intl Group Inc',
    'AMT': 'American Tower Corp',
    'AAPL': 'Apple Inc',
    'AMAT': 'Applied Materials',
    'BAC': 'Bank of America',
    'BA': 'Boeing Co',
    'BRCM': 'Broadcom Corp',
    'CA': 'CA Inc',
    'CAT': 'Caterpillar Inc',
    'CVX': 'Chevron',
    'CSCO': 'Cisco Systems Inc',
    'C': 'Citigroup Inc',
    'KO': 'Coca-Cola co',
    'GLW': 'Corning Inc',
    'DD': 'DuPont',
    'EMC': 'EMC Corp',
    'EK': 'Eastman Kodak',
    'XOM': 'Exxon Mobil',
    'FSLR': 'First Solar Inc',
    'GE': 'GE',
    'HPQ': 'Hewlett-Packard',
    'HD': 'Home Depot',
    'IBM': 'IBM',
    'IP': 'Int.Paper',
    'INTC': 'Intel Corp',
    'JPM': 'JPMorgan Chase&Co',
    'JNJ': 'Johnson & Johnson',
    'MO': 'Kraft Foods',
    'MCD': 'McDonalds',
    'MRK': 'Merck & Co',
    'MSFT': 'Microsoft Corp',
    'PFE': 'Pfizer Inc',
    'PG': 'Procter & Gamble',
    'TRV': 'Travelers Comp',
    'UTX': 'United Technologies',
    'VZ': 'Verizon Communications',
    'WMT': 'Wal-Mart Stores',
    'DIS': 'Walt Disney',
    'WFC': 'Wells Fargo',
    'YHOO': 'Yahoo INC'
}
